package com.aistudio.rkaiassistant.data

import android.content.Context
import com.google.mediapipe.tasks.genai.llminference.LlmInference
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

object LocalLLMService {
    private var llmInference: LlmInference? = null
    private var isInitialized = false

    const val MODEL_PATH = "rk_ai_engine_v2.bin"
    const val MODEL_URL = "https://storage.googleapis.com/mediapipe-models/llm/gemma-2b-it-gpu-int4.bin"

    private var lastInitError: String? = null

    fun getLastError(): String? = lastInitError

    fun getTargetModelFile(context: Context): File {
        val extDir = context.getExternalFilesDir(null)
        return if (extDir != null) File(extDir, MODEL_PATH) else File(context.filesDir, MODEL_PATH)
    }

    fun getModelFile(context: Context): File {
        val extDir = context.getExternalFilesDir(null)
        val externalFile = if (extDir != null) File(extDir, MODEL_PATH) else null
        val internalFile = File(context.filesDir, MODEL_PATH)

        return when {
            externalFile?.exists() == true && externalFile.length() > 100 * 1024 * 1024 -> externalFile
            internalFile.exists() && internalFile.length() > 100 * 1024 * 1024 -> internalFile
            else -> externalFile ?: internalFile
        }
    }

    fun initialize(context: Context) {
        if (isInitialized && llmInference != null) return
        
        lastInitError = null
        val modelFile = getModelFile(context)

        if (!modelFile.exists() || modelFile.length() < 100 * 1024 * 1024) {
            val err = "Model file not found or too small: ${modelFile.absolutePath}"
            android.util.Log.e("RKAI", err)
            lastInitError = err
            return
        }

        try {
            android.util.Log.d("RKAI", "Initializing LlmInference with ${modelFile.absolutePath}")
            val options = LlmInference.LlmInferenceOptions.builder()
                .setModelPath(modelFile.absolutePath)
                .setMaxTokens(1024)
                .build()

            llmInference = LlmInference.createFromOptions(context, options)
            isInitialized = true
            android.util.Log.d("RKAI", "LlmInference initialized successfully")
        } catch (e: Throwable) {
            val err = "LlmInference failed: ${e.localizedMessage ?: e.message}"
            android.util.Log.e("RKAI", err)
            isInitialized = false
            llmInference = null
            lastInitError = err
            
            if (e is Exception && e.message?.contains("Invalid magic number", ignoreCase = true) == true) {
                modelFile.delete()
            }
        }
    }

    suspend fun generateResponse(prompt: String, context: Context? = null): String = withContext(Dispatchers.IO) {
        if (!isInitialized || llmInference == null) {
            if (context != null) {
                initialize(context)
            }
            
            if (!isInitialized || llmInference == null) {
                return@withContext "Engine Error: ${lastInitError ?: "Model file missing. Please re-import in settings."}"
            }
        }

        try {
            val response = llmInference?.generateResponse(prompt)
            if (response.isNullOrBlank()) "System: No response generated by local AI." else response
        } catch (e: Exception) {
            "Local AI Runtime Error: ${e.localizedMessage}"
        }
    }

    fun isEngineReady(): Boolean = isInitialized && llmInference != null

    fun isModelAvailable(context: Context): Boolean {
        val file = getModelFile(context)
        return file.exists() && file.length() > 100 * 1024 * 1024
    }

    fun reset() {
        isInitialized = false
        llmInference?.close()
        llmInference = null
    }
}
